Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,28 +31,28 @@ jobs:
         uses: actions/checkout@v4
       # Install the cosign tool except on PR
       # https://github.com/sigstore/cosign-installer
-      - name: Install cosign
-        if: github.event_name != 'pull_request'
-        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
-        with:
-          cosign-release: 'v2.2.4'
-      - uses: actions/setup-java@v5
-        with:
-          distribution: 'jetbrains'
-          java-version: '21'
-          cache: 'maven'
-      - name: Run and Test with Maven - Product Service
-        run:  mvn clean verify -B
-        working-directory: product-service
-      - name: Run and Test with Maven - Order Service
-        run:  mvn clean verify -B
-        working-directory: order-service
-      - name: Unit Test Report
-        uses: actions/upload-artifact@v4
-        if: success() || failure()
-        with:
-          name: SpringBoot Report
-          path: test-output/
+      # - name: Install cosign
+      #   if: github.event_name != 'pull_request'
+      #   uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
+      #   with:
+      #     cosign-release: 'v2.2.4'
+      # - uses: actions/setup-java@v5
+      #   with:
+      #     distribution: 'jetbrains'
+      #     java-version: '21'
+      #     cache: 'maven'
+      # - name: Run and Test with Maven - Product Service
+      #   run:  mvn clean verify -B
+      #   working-directory: product-service
+      # - name: Run and Test with Maven - Order Service
+      #   run:  mvn clean verify -B
+      #   working-directory: order-service
+      # - name: Unit Test Report
+      #   uses: actions/upload-artifact@v4
+      #   if: success() || failure()
+      #   with:
+      #     name: SpringBoot Report
+      #     path: test-output/
 
   docker-build:
     runs-on: ubuntu-latest
@@ -64,7 +64,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Build image
-        run: docker build -t productservice
+        run: docker build -t productservice .
         working-directory: product-service
       # - name: Log in to Docker Hub
       #   uses: docker/login-action@v3
@@ -136,7 +136,7 @@ jobs:
       #   # This step uses the identity token to provision an ephemeral certificate
       #   # against the sigstore community Fulcio instance.
       #   run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
-      - name: Code Linter
-        uses: github/super-linter@v4
-        env:
-          VALIDATE_ALL_CODEBASE: true
+      # - name: Code Linter
+      #   uses: github/super-linter@v4
+      #   env:
+      #     VALIDATE_ALL_CODEBASE: true
